### ISSUE TITLE
Upgrade to Solr 7.2.1

### ISSUE THREAD

**Issue by BorisNaguet** [BorisNaguet/solr-maven-plugin#10]
This will require Java 8

**Comment by yourfrienddhruv** [comment]
eagerly waiting for this release 0.5.0 to be available on maven central.
Thanks for the good work!

**Comment by BorisNaguet** [comment]
it's already available:
http://search.maven.org/#artifactdetails%7Cio.github.borisnaguet%7Csolr-maven-plugin%7C0.5.0%7C
