### ISSUE TITLE
Help: How to configure plugin to log only WARN level logs for SOLR

### ISSUE THREAD

**Issue by yourfrienddhruv** [BorisNaguet/solr-maven-plugin#11]
Maven build logs are full due to INFO logs of this plugin

>[INFO] [IW][coreCloseExecutor-203-thread-14]: apply all deletes during flush
> [INFO] [IW][coreCloseExecutor-203-thread-14]: now apply all deletes for all segments maxDoc=0
> [INFO] [BD][coreCloseExecutor-203-thread-14]: prune sis=segments_1:  minGen=9223372036854775807 packetCount=0
> [INFO] [DW][coreCloseExecutor-203-thread-14]: coreCloseExecutor-203-thread-14 finishFullFlush success=true
> [INFO] [IW][coreCloseExecutor-203-thread-14]: startCommit(): start
> [INFO] [IW][coreCloseExecutor-203-thread-14]:   skip startCommit(): no changes pending
> [INFO] [IW][coreCloseExecutor-203-thread-14]: commit: pendingCommit == null; skip
> [INFO] [IW][coreCloseExecutor-203-thread-14]: commit: took 16.5 msec
> [INFO] [IW][coreCloseExecutor-203-thread-14]: commit: done
> [INFO] [IW][coreCloseExecutor-203-thread-14]: rollback
> [INFO] [IW][coreCloseExecutor-203-thread-14]: all running merges have aborted
> [INFO] [IW][coreCloseExecutor-203-thread-14]: rollback: done finish merges
> [INFO] [DW][coreCloseExecutor-203-thread-14]: abort
> [INFO] [DW][cor

**Comment by BorisNaguet** [comment]
Hello!

This plugin uses standard Maven configuration for logging:
https://maven.apache.org/maven-logging.html

So it's based on SLF4J, and it uses this SimpleLogger:
https://www.slf4j.org/apidocs/org/slf4j/impl/SimpleLogger.html

With that, you can configure everything:
* in your `simplelogger.properties`
* or (certainly better) in the command line (with `-Dproperty=value`)

For example, if you want to know the name of the logger, just use:
`org.slf4j.simpleLogger.showLogName=true`
You'll probably see that your logs comes from these 2 packages:
* `org.apache.solr.*`
* `org.apache.zookeeper.*`

So this command line should remove the INFO logs:
```
-Dorg.slf4j.simpleLogger.log.org.apache.solr=warn -Dorg.slf4j.simpleLogger.log.org.apache.zookeeper=warn
```

**Comment by yourfrienddhruv** [comment]
Thanks! added to maven.config and works like a charm!
